#!/usr/bin/env python3
"""Extract `ID: text` lines from code blocks in story.md into js/text_data.js."""
import json, re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
s = (root / 'story.md').read_text()
out = {}
for block in re.findall(r'```[^\n]*\n(.*?)```', s, re.S):
    for line in block.split('\n'):
        m = re.match(r'^([A-Z][A-Z0-9_]+):\s*(.*)$', line)
        if m:
            out[m.group(1)] = m.group(2).strip()
js = '// Generated by tools/extract_text.py from story.md. Do not edit by hand.\nexport const STORY = ' + json.dumps(out, ensure_ascii=False, indent=0) + ';\n'
(root / 'js' / 'text_data.js').write_text(js)
print(len(out), 'lines')
